package com.adrianrossino.auth;

import static org.junit.Assert.*;

import java.io.IOException;
import java.security.GeneralSecurityException;
import com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.Payload;

import org.junit.Test;

import com.adrianrossino.common.InvalidTokenException;

public class GoogleTokenVerifierTest {

	@Test
	public void test() {
		GoogleTokenVerifier verifier = new GoogleTokenVerifier();
		String idTokenString = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhhNjNmZTcxZTUzMDY3NTI0Y2JiYzZhM2E1ODQ2M2IzODY0YzA3ODciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiMTAyOTk4OTIwNDA2My04M2JyN2JlanRsMWE2a2pvbTRsN2FwMWVyMm5xNnJhai5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjEwMjk5ODkyMDQwNjMtODNicjdiZWp0bDFhNmtqb200bDdhcDFlcjJucTZyYWouYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTU0ODAyNTkzNTkxMjIxNDI3MTUiLCJlbWFpbCI6Imd1cmRvbWFuQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoid3NqS205Y09OVTh2QkJ4S0tqdGRBdyIsIm5hbWUiOiJBZHJpYW4gUm9zc2lubyIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS0vQUF1RTdtQzV4SUdfMUFoYmxhTWpQdzlSQ2x6dndRZmo5bzBmam02YVJwOWFxMTg9czk2LWMiLCJnaXZlbl9uYW1lIjoiQWRyaWFuIiwiZmFtaWx5X25hbWUiOiJSb3NzaW5vIiwibG9jYWxlIjoiZW4iLCJpYXQiOjE1NzIxNjc0MDIsImV4cCI6MTU3MjE3MTAwMiwianRpIjoiMzg0MDFmMjVmMjMwY2M3OWQxNGU0YzAxMzdlNmQwOTE1NWE2ZWVmMiJ9.ZfyYt8AC2llQkIYp-EgIlpWfTE_hSd1zdi6776i4rNhXRVw2tGIZYl0PEoqHLHSc7SgutVAMhJWX_C3nQtRt8_jfvFmqYTD5FrxKNC-AIBxg2sYEtDwglghVWmCN4_UTK7q0a9sk3B59D0msrqWV4gapxldS-WdViFZUa77oasY1muI9XYb_-T0QENcz60DJ_uen8qXp2EnDLOxreqi-SkXvLpKtAaOlwBNj5zTeoGL4l4IJcHGxsES-V5dQjkOIOC7bvIc2bd_f1f7XrX8Kyk23fdVhe48derUW2YUsWyDTbZemLZU1AgBybLlnrpUuXDwordOlct8Bc6PEzS1QTA";
		
		try {
			Payload testUser = verifier.verify(idTokenString);
			assertEquals(testUser.getEmail(), "gurdoman@gmail.com");
		} catch (GeneralSecurityException | IOException | InvalidTokenException e) {
			e.printStackTrace();
		}
	}

}
